#!/usr/bin/env bash
# setup-env.sh — Interactive .env wizard for fab.engineering
# Run: bash setup-env.sh

set -e

RED='\033[0;31m'; YELLOW='\033[1;33m'; GREEN='\033[0;32m'; CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

echo ""
echo -e "${BOLD}${CYAN}fab.engineering — Kurulum Sihirbazı${NC}"
echo -e "${CYAN}─────────────────────────────────────${NC}"
echo ""

# ── Domain ────────────────────────────────────────────────────────────────────
echo -e "${BOLD}1. Alan Adı${NC}"
echo "  Platforma erişmek için kullanılacak alan adı (ör. agents.sirketim.com)"
read -rp "  > " DOMAIN
DOMAIN="${DOMAIN:-localhost}"
echo ""

# ── Company info ──────────────────────────────────────────────────────────────
echo -e "${BOLD}2. Şirket Bilgileri${NC}"
read -rp "  Şirket adı: " COMPANY_NAME
read -rp "  Sektör (ör. Yazılım, Lojistik): " COMPANY_SECTOR
COMPANY_WEBSITE="https://${DOMAIN}"
echo ""

# ── Secrets (auto-generate) ───────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
ENCRYPTION_KEY=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")

echo -e "${BOLD}3. Güvenlik Anahtarları${NC} (otomatik oluşturuldu)"
echo -e "  JWT_SECRET:      ${GREEN}✓ oluşturuldu${NC}"
echo -e "  ENCRYPTION_KEY:  ${GREEN}✓ oluşturuldu${NC}"
echo ""

# ── AI Provider keys (optional) ───────────────────────────────────────────────
echo -e "${BOLD}4. AI Sağlayıcı Anahtarları${NC} ${YELLOW}(isteğe bağlı — Ayarlar sayfasından da eklenebilir)${NC}"
read -rp "  Anthropic API Key (boş bırakabilirsiniz): " ANTHROPIC_API_KEY
read -rp "  OpenAI API Key (boş bırakabilirsiniz): " OPENAI_API_KEY
read -rp "  Google API Key (boş bırakabilirsiniz): " GOOGLE_API_KEY
echo ""

# ── Email notifications (optional) ───────────────────────────────────────────
echo -e "${BOLD}5. E-posta Bildirimleri${NC} ${YELLOW}(isteğe bağlı)${NC}"
echo "  Telegram ile de yapılandırılabilir — Ayarlar → Entegrasyonlar"
read -rp "  Gönderici e-posta (ör. noreply@sirketim.com): " EMAIL_FROM
EMAIL_FROM="${EMAIL_FROM:-noreply@fab.limited}"
echo ""

# ── Opt-in registration ───────────────────────────────────────────────────────
echo -e "${BOLD}6. Güncelleme Bildirimleri${NC} ${YELLOW}(isteğe bağlı — MIT lisanslı, herhangi bir ücret yoktur)${NC}"
echo "  Yeni sürüm bildirimlerini e-posta ile almak ister misiniz?"
read -rp "  Ad Soyad (boş bırakabilirsiniz): " REG_NAME
read -rp "  E-posta (boş bırakabilirsiniz): " REG_EMAIL
echo ""

# ── Write .env ────────────────────────────────────────────────────────────────
APP_URL="https://${DOMAIN}"
if [ "$DOMAIN" = "localhost" ]; then
    APP_URL="http://localhost:5173"
fi

cat > .env << EOF
# fab.engineering — Production Environment
# Generated by setup-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# ── Core ───────────────────────────────────────────────────────────────────────
DOMAIN=${DOMAIN}
APP_URL=${APP_URL}

# ── Security (DO NOT SHARE) ────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# ── Company ────────────────────────────────────────────────────────────────────
COMPANY_NAME=${COMPANY_NAME}
COMPANY_SECTOR=${COMPANY_SECTOR}
COMPANY_WEBSITE=${COMPANY_WEBSITE}

# ── Notifications ──────────────────────────────────────────────────────────────
EMAIL_FROM=${EMAIL_FROM}

# ── AI Providers (optional — can also be set via Settings UI) ─────────────────
EOF

[ -n "$ANTHROPIC_API_KEY" ] && echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" >> .env
[ -n "$OPENAI_API_KEY" ]    && echo "OPENAI_API_KEY=${OPENAI_API_KEY}" >> .env
[ -n "$GOOGLE_API_KEY" ]    && echo "GOOGLE_API_KEY=${GOOGLE_API_KEY}" >> .env

echo -e "${GREEN}✓ .env dosyası oluşturuldu${NC}"
echo ""

# ── Send opt-in registration ──────────────────────────────────────────────────
if [ -n "$REG_EMAIL" ]; then
    echo -n "  Kayıt gönderiliyor... "
    curl -sf -X POST "https://api.fab.limited/install-register" \
        -H "Content-Type: application/json" \
        -d "{\"name\":\"${REG_NAME}\",\"email\":\"${REG_EMAIL}\",\"domain\":\"${DOMAIN}\"}" \
        --max-time 5 > /dev/null 2>&1 && echo -e "${GREEN}✓${NC}" || echo -e "${YELLOW}(bağlantı kurulamadı, atlandı)${NC}"
fi

echo ""
