"""add_providerkey_base_url

Revision ID: 48b730a4a8bb
Revises: bc1b925344f3
Create Date: 2026-07-09 12:55:07.236063

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48b730a4a8bb"
down_revision: str | Sequence[str] | None = "bc1b925344f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("providerkey", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("base_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("providerkey", schema=None) as batch_op:
        batch_op.drop_column("base_url")

    # ### end Alembic commands ###
